version: '3.8'
services:
  api:
    build: .
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dockernet

networks:
  dockernet:
    external: true
